### ISSUE TITLE
Handling responses with non-200 code

### ISSUE THREAD

**Issue by Baka9k** [jomaxx/superagent-promise-plugin#7]
How to get data from response, if it has non-200 http code? I can't use `.then((res) => {if res.status ...` like in fetch https://github.com/github/fetch/issues/203 , because `then` handler doesn't execute when response code is not 200, and in `.catch` I can't get anything besides error object.

**Comment by danikaze** [comment]
It exists, but not for 404 (i.e. 400, 500...)
Fetch API only rejects the promise when there's a network problem (like in 404 - resource not found)
https://stackoverflow.com/a/38236296
